### ISSUE TITLE
Missing configuration in game

### ISSUE THREAD

**Issue by AlisterGontineac** [Fuzss/stylisheffects-fabric#1]
StylishEffects-v2.0.1-1.17.1-Fabric has no configuration options in game. ( missing configuration )
I don't know if it is due to another mod or what, but none of your mods are configurable, there is no option in modmenu.
TradingPost, Pick Up Notifier, Easy Magic, none of them.

**Comment by EGOIST1372** [comment]
please add modmenu config
thanks in advance

**Comment by Fuzss** [comment]
It hasn't been implemented.
