### ISSUE TITLE
Incompatibility with Bedrockify

### ISSUE THREAD

**Issue by CapoFantasma97** [Fuzss/stylisheffects-fabric#2]
The HUD part of the mod doesn't work when [Bedrockify](https://www.curseforge.com/minecraft/mc-mods/bedrockify) is installed. The part inside inventories is still functional however.

Stylish Effects 2.0.1 for Minecraft 1.17.1

![immagine](https://user-images.githubusercontent.com/9368910/147699019-60c7be72-ba0e-4d96-9d6d-147fbda8b363.png)

**Comment by Fuzss** [comment]
Ah, you're still on 1.17. I fixed that for 1.18 already, on 1.17 you can disable the screen safe area mixin in the bedrockify mixin config. After that you'll have to restart your game, then it'll work.

**Comment by Fuzss** [comment]
As mentioned this is fixed on newer versions and on 1.17 the Bedrockify mixin can be disabled, therefore closing this issue now.
